name: yt-dlp GUI CI Builder

on:
  release:
    types: [created]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest
    
    env:
      Solution_Name: yt-dlp-gui.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.400

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore the application
      run: dotnet restore $env:Solution_Name
    
    - name: Build
      run: dotnet publish -c ${{ matrix.configuration }} -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o ./publish_output
    
    - name: Verify Build
      run: |
        $exePath = "./publish_output/yt-dlp-gui.exe"
        Write-Host "Looking for executable at $exePath"
        if (-not (Test-Path $exePath)) {
          Write-Error "Executable not found at $exePath"
          Get-ChildItem -Path ./publish_output -Recurse
          exit 1
        }
        Write-Host "Attempting to start $exePath"
        Start-Process $exePath
        Write-Host "Waiting for 5 seconds..."
        Start-Sleep -Seconds 5
        $process = Get-Process yt-dlp-gui -ErrorAction SilentlyContinue
        if ($null -eq $process) {
          Write-Error "Process yt-dlp-gui did not start or crashed."
          exit 1
        } else {
          Write-Host "Process yt-dlp-gui started successfully. Killing it now."
          Stop-Process -Name yt-dlp-gui -Force
          Write-Host "Process killed."
          exit 0
        }
      shell: pwsh

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish_output/yt-dlp-gui.exe
        asset_name: yt-dlp-gui.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: yt-dlp-gui-${{ github.run_number }}-${{ matrix.configuration }}
        path: ./publish_output
